### ISSUE TITLE
Videogular-Quiz Broken

### ISSUE THREAD

**Issue by harshithkashyap** [NamPNQ/bower-videogular-quiz#5]
The project seems to be completely inactive but this is broken with the latest videogular(0.7.2). The VG_EVENTS seems to be deprecated from videogular from 0.5 release. I tried removing the VG_EVENTS and use this instead. But this doesn't work either. Returns undefined
<pre>API.$on('onUpdateTime', onUpdateTime);</pre>

**Comment by NamPNQ** [comment]
Sorry, i discontinue support videogular-quiz for new version
