### ISSUE TITLE
Update Quiz plugin to work with latest Videogular version

### ISSUE THREAD

**Issue by hecnabae** [NamPNQ/bower-videogular-quiz#6]
Hey,
Is that possible to update the plugin to make it work with the latest Videogular version?

Current plugin's version throws this error when click on play:
'TypeError: Cannot read property '0' of undefined at play (videogular.js:287)...'

Thank you!

**Comment by NamPNQ** [comment]
Sr @hecnabae , i'm very busy, not enough time for update
